spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: sustc  # change this to your own username (avoid using a superuser)
    password: sustc  # change this to your own password

    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
